
#######################################################
{SCRIPT_VARS}
#######################################################
SOLUTE            $1.N$      $195.O$

#######################################################
{GENERAL}
#######################################################
[MD]
stepsize                 1
steps                   200
temperature             300
initial_temperature     300
random_seed             123435 
bath_coupling            10 
lrf                      on
shake_solvent            on

[cut-offs]
solute_solute             10
solute_solvent            10
solvent_solvent           10
q_atom                    99

[intervals]
non_bond                 30
output                	500
trajectory              500  
temperature             200

[distance_restraints]
$49.SG$    $196.O1$     0.0  3.2  10. 0 
$83.OE1$   $196.O1$     0.0  3.2  10. 0  
$49.SG$    $49.HG1$     0.0  1.5   5. 1
$196.O1$   $196.H1$     0.0  1.5   5. 1 
$83.OE1$   $196.H1$     0.0  1.5   5. 2 
$196.O1$   $49.HG1$     0.0  1.5   5. 2 

#######################################################
{STEPS_EQUIL}
#######################################################

# solvent heat-up 
 
[MD] 
initial_temperature      1 
temperature              1 
random_seed              -1

[sequence_restraints] 
SOLUTE     10.0 0 0 0 
_____________________________________________________________ 
 
[MD] 
temperature             100 
 
[sequence_restraints] 
SOLUTE     10.0 0 0 0 
_____________________________________________________________ 
 
[MD] 
 
[sequence_restraints] 
SOLUTE     10.0 0 0 0 
_____________________________________________________________ 
 
# releasing restraints 
 
[MD] 
 
[sequence_restraints] 
SOLUTE      5.0 0 0 0 
_____________________________________________________________ 
 
[MD] 
 
[sequence_restraints] 
SOLUTE      2.0 0 0 0 
_____________________________________________________________ 
 
[MD] 
 
[sequence_restraints] 
SOLUTE      1.0 0 0 0 
_____________________________________________________________ 
 
[MD] 
 
[sequence_restraints] 
SOLUTE      0.5 0 0 0 
 
_____________________________________________________________ 
 
[MD] 
 
[sequence_restraints] 
SOLUTE      0.1 0 0 0 
______________________________________________________

[MD] 
______________________________________________________
#######################################################
{FEP}
#######################################################
[MD]

[intervals]
energy                   5
random_seed           78992
trajectory	           500
output                 500
