In [1]:
import pandas as pd

# List of mutants
mutants = [3, 4, 16, 22, 24, 25, 27, 29, 30, 31, 33, 35, 40, 47, 
           48, 49, 52, 54, 60, 67, 69, 71, 74, 87, 99, 102, 104, 
           107, 119, 120, 126, 137, 139, 142, 143, 144, 148, 
           173, 177, 178, 181, 182, 184, 188, 192, 194, 195]

# Example energies for each mutant; replace these with actual values
energy_values = {
    3: 1.2, 4: 0.8, 16: 1.0, 22: 1.5, 24: 0.5, 25: 1.3, 
    27: 0.9, 29: 1.1, 30: 0.4, 31: 0.6, 33: 1.4, 35: 0.7, 
    40: 1.2, 47: 0.3, 48: 1.6, 49: 1.3, 52: 1.1, 54: 0.9, 
    60: 1.5, 67: 1.2, 69: 1.4, 71: 0.8, 74: 1.1, 87: 1.0, 
    99: 0.5, 102: 1.2, 104: 0.7, 107: 1.3, 119: 1.0, 
    120: 1.1, 126: 1.4, 137: 0.9, 139: 1.5, 142: 1.3, 
    143: 1.6, 144: 0.4, 148: 1.2, 173: 1.1, 177: 0.8, 
    178: 1.5, 181: 1.3, 182: 0.7, 184: 1.4, 188: 0.9, 
    192: 1.2, 194: 1.6, 195: 0.3
}

# Create a DataFrame for easier manipulation
data = pd.DataFrame(list(energy_values.items()), columns=['mutant_name', 'energy'])

# List to hold selected mutants
selected_mutants = []

# Process until all mutants are used
while not data.empty:
    # Find the mutant with the lowest energy
    lowest_energy_mutant = data.loc[data['energy'].idxmin()]
    
    # Append to the results list
    selected_mutants.append(lowest_energy_mutant['mutant_name'])
    
    # Remove that mutant from the original list
    data = data[data['mutant_name'] != lowest_energy_mutant['mutant_name']]
    
    # Remove the lowest energy mutant from the initial mutants list for the next iterations
    mutants.remove(lowest_energy_mutant['mutant_name'])

# Print the selected mutants in order of their selection
print("Selected mutants in order of lowest energy:")
print(selected_mutants)

# Create a DataFrame from the selected mutants for saving to CSV
selected_df = pd.DataFrame(selected_mutants, columns=['selected_mutants'])

# Save the selected mutants to a CSV file
csv_file_path = '/home/hp/nayanika/github/GPX6/analysis/structure_analysis/selected_mutants.csv'
selected_df.to_csv(csv_file_path, index=False)

# Print the number of selected mutants saved
print(f"Number of selected mutants saved: {len(selected_mutants)}")
print(f"Selected mutants saved to CSV file: {csv_file_path}")


Selected mutants in order of lowest energy:
[47.0, 195.0, 30.0, 144.0, 24.0, 99.0, 31.0, 35.0, 104.0, 182.0, 4.0, 71.0, 177.0, 27.0, 54.0, 137.0, 188.0, 16.0, 87.0, 119.0, 29.0, 52.0, 74.0, 120.0, 173.0, 3.0, 40.0, 67.0, 102.0, 148.0, 192.0, 25.0, 49.0, 107.0, 142.0, 181.0, 33.0, 69.0, 126.0, 184.0, 22.0, 60.0, 139.0, 178.0, 48.0, 143.0, 194.0]
Number of selected mutants saved: 47
Selected mutants saved to CSV file: /home/hp/nayanika/github/GPX6/analysis/structure_analysis/selected_mutants.csv


Breakdown of the Output:
Selected Mutants: The list contains the names (or identifiers) of the mutants in the order they were chosen, starting with the one that has the lowest energy.
Values: Each number corresponds to a specific mutant from your original list of 47 mutants.
Example Interpretation:
47.0: This means that mutant 47 had the lowest energy value among all the mutants and was selected first.
195.0: After selecting mutant 47, mutant 195 had the next lowest energy and was selected second, and so on.

In [ ]:
import matplotlib.pyplot as plt
from itertools import combinations

# Define the specific mutant positions for combination
specific_positions = [47, 48, 52, 99,]

# Define the group sizes (you can choose 2, 3, or 4 combinations)
group_sizes = [2, 3, 4]

# Prepare data for plotting
table_data = [["Positions"]]

# Generate combinations and add to table data
for size in group_sizes:
    # Only generate combinations if there are enough positions
    if size <= len(specific_positions):
        combos = list(combinations(specific_positions, size))  # Generate combinations
        
        for combo in combos:
            summation_str = " + ".join(map(str, combo))
            table_data.append([summation_str])

# Plot as a table in a figure with only the Positions column
fig, ax = plt.subplots(figsize=(10, 10))  # Adjust figure size to reduce white space
ax.axis('off')
table = ax.table(cellText=table_data, cellLoc="center", loc="center", colColours=["skyblue"])
table.auto_set_font_size(False)
table.set_fontsize(12)
table.scale(2, 1.5)  # Further scale to increase visibility

# Center the table within the figure
table_position = ax.get_position()
table_position = [table_position.x0 + 0.15, table_position.y0 + 0.15, 0.7, 0.7]  # Center the table
ax.set_position(table_position)

# Save as PNG
output_image = "/home/hp/results/mutant_combinations_positions_summation_10.png"
plt.savefig(output_image, dpi=100, bbox_inches="tight")
plt.show()

print(f"PNG visualization saved to {output_image}")
